/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    solutions: Solution;
    sectors: Sector;
    projects: Project;
    insights: Insight;
    faqs: Faq;
    leads: Lead;
    'lead-activities': LeadActivity;
    careers: Career;
    'job-applications': JobApplication;
    testimonials: Testimonial;
    clients: Client;
    certifications: Certification;
    'team-members': TeamMember;
    media: Media;
    users: User;
    redirects: Redirect;
    'audit-logs': AuditLog;
    'analytics-daily': AnalyticsDaily;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'lead-activities': LeadActivitiesSelect<false> | LeadActivitiesSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'analytics-daily': AnalyticsDailySelect<false> | AnalyticsDailySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    homepage: Homepage;
    'about-page': AboutPage;
    'quality-safety-page': QualitySafetyPage;
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'contact-settings': ContactSetting;
    'seo-settings': SeoSetting;
    'analytics-settings': AnalyticsSetting;
    'notification-settings': NotificationSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'quality-safety-page': QualitySafetyPageSelect<false> | QualitySafetyPageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'contact-settings': ContactSettingsSelect<false> | ContactSettingsSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
    'analytics-settings': AnalyticsSettingsSelect<false> | AnalyticsSettingsSelect<true>;
    'notification-settings': NotificationSettingsSelect<false> | NotificationSettingsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * مثال: about، quality-safety، privacy، careers
   */
  slug: string;
  subtitle?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * عنوان ووصف الصفحة في نتائج البحث ومشاركات التواصل.
   */
  seo?: {
    /**
     * 60 حرفًا تقريبًا. اتركه فارغًا لاستخدام العنوان الافتراضي.
     */
    metaTitle?: string | null;
    /**
     * 155 حرفًا تقريبًا.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * مكتبة الصور والملفات — لكل صورة نص بديل بالعربي والإنجليزي.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  altAr: string;
  altEn: string;
  captionAr?: string | null;
  captionEn?: string | null;
  /**
   * مثال: تصوير ميداني — اجتياز الخليج، 2026.
   */
  credit?: string | null;
  category?: ('team' | 'sites' | 'equipment' | 'projects' | 'client-logos' | 'other') | null;
  tags?: string[] | null;
  /**
   * اترك هذا الخيار غير مفعّل لأي صورة (خصوصًا شعارات العملاء) حتى تصل موافقة استخدام موثقة.
   */
  usageApproved?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * عائلات وخدمات الحلول الثمانية المعروضة في /solutions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  /**
   * يظهر في الرابط: /solutions/<slug>
   */
  slug: string;
  icon: 'wrench' | 'sparkles' | 'hammer' | 'leaf' | 'plane' | 'bug' | 'concierge' | 'home';
  featured?: boolean | null;
  sortOrder?: number | null;
  summary: string;
  heroOutcome: string;
  problem: string;
  scope?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  sectors?: (number | Sector)[] | null;
  methodology: string;
  quality: string;
  heroImage?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * عنوان ووصف الصفحة في نتائج البحث ومشاركات التواصل.
   */
  seo?: {
    /**
     * 60 حرفًا تقريبًا. اتركه فارغًا لاستخدام العنوان الافتراضي.
     */
    metaTitle?: string | null;
    /**
     * 155 حرفًا تقريبًا.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  title: string;
  slug: string;
  icon: 'office' | 'health' | 'residential' | 'industrial' | 'education' | 'airport' | 'government';
  sortOrder?: number | null;
  summary: string;
  challenges?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  relevantSolutions?: (number | Solution)[] | null;
  /**
   * كيف نموذج التشغيل المناسب لهذا القطاع.
   */
  operatingModel?: string | null;
  media?: (number | null) | Media;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * عنوان ووصف الصفحة في نتائج البحث ومشاركات التواصل.
   */
  seo?: {
    /**
     * 60 حرفًا تقريبًا. اتركه فارغًا لاستخدام العنوان الافتراضي.
     */
    metaTitle?: string | null;
    /**
     * 155 حرفًا تقريبًا.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * لا يظهر أي مشروع في الموقع العام إلا إذا كانت حالته Published وverificationStatus = verified معًا.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  /**
   * لا يظهر أي عنصر بحالة غير "موثّق ومعتمد" في الموقع العام.
   */
  verificationStatus: 'unverified' | 'pending' | 'verified' | 'rejected';
  workflowStatus?: ('draft' | 'review' | 'approved' | 'published' | 'archived') | null;
  confidentialityMode?: ('named' | 'confidential') | null;
  /**
   * عند اختيار "سري" اكتب وصفًا عامًا مثل "جهة في القطاع الصحي" بدل اسم العميل الفعلي.
   */
  clientDisplayName: string;
  sector?: (number | null) | Sector;
  relatedSolutions?: (number | Solution)[] | null;
  city?: string | null;
  contractStartDate?: string | null;
  contractEndDate?: string | null;
  /**
   * مثال: عقد سنوي متجدد.
   */
  durationLabel?: string | null;
  challenge: string;
  scope: string;
  solutionApproach: string;
  /**
   * لا تُضف مؤشرًا هنا إلا برقم موثّق من العميل أو من فريق التشغيل.
   */
  kpis?:
    | {
        label: string;
        beforeValue?: string | null;
        afterValue?: string | null;
        /**
         * مصدر الرقم (داخلي فقط، لا يُنشر).
         */
        sourceNote?: string | null;
        id?: string | null;
      }[]
    | null;
  gallery?: (number | Media)[] | null;
  testimonial?: {
    quote?: string | null;
    attribution?: string | null;
    approved?: boolean | null;
  };
  /**
   * إثبات موافقة العميل (بريد/خطاب) — داخلي فقط، لا يظهر على الموقع العام.
   */
  approvalEvidence?: (number | null) | Media;
  /**
   * عنوان ووصف الصفحة في نتائج البحث ومشاركات التواصل.
   */
  seo?: {
    /**
     * 60 حرفًا تقريبًا. اتركه فارغًا لاستخدام العنوان الافتراضي.
     */
    metaTitle?: string | null;
    /**
     * 155 حرفًا تقريبًا.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cover?: (number | null) | Media;
  category?: ('maintenance' | 'facility-management' | 'quality-safety' | 'buyers-guide') | null;
  tags?: string[] | null;
  author?: (number | null) | User;
  readingTimeMinutes?: number | null;
  publishedAt?: string | null;
  /**
   * عنوان ووصف الصفحة في نتائج البحث ومشاركات التواصل.
   */
  seo?: {
    /**
     * 60 حرفًا تقريبًا. اتركه فارغًا لاستخدام العنوان الافتراضي.
     */
    metaTitle?: string | null;
    /**
     * 155 حرفًا تقريبًا.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * لوحة الوصول: من يستطيع الدخول للوحة التحكم ودوره.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * super-admin: كل الصلاحيات · content-manager: المحتوى والوسائط · sales: الطلبات والعملاء · analyst: التقارير فقط · viewer: قراءة فقط.
   */
  roles: ('super-admin' | 'content-manager' | 'sales' | 'analyst' | 'viewer')[];
  /**
   * عطّل هذا الخيار لإيقاف دخول المستخدم دون حذف حسابه.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * أسئلة عامة (غير مرتبطة بحل معيّن) تُستخدم حيث يلزم عبر الموقع.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  topic?: ('general' | 'quotes' | 'quality' | 'careers') | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * طلبات المعاينة والعروض والاهتمام الوظيفي الواردة من الموقع.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  referenceNumber: string;
  type: 'business' | 'home' | 'career' | 'other';
  status: 'new' | 'contacted' | 'qualified' | 'site-visit' | 'scheduled' | 'proposal-sent' | 'won' | 'lost' | 'spam';
  priority?: ('low' | 'normal' | 'high') | null;
  assignedTo?: (number | null) | User;
  followUpAt?: string | null;
  lossReason?: string | null;
  name: string;
  company?: string | null;
  email: string;
  phone: string;
  preferredContact?: ('phone' | 'whatsapp' | 'email') | null;
  service?: (number | null) | Solution;
  /**
   * قيمة الخدمة كما أُرسلت من النموذج (احتياطي إن تعذّر ربطها بسجل حل).
   */
  serviceSlug?: string | null;
  sector?: (number | null) | Sector;
  sectorSlug?: string | null;
  city?: string | null;
  message?: string | null;
  attachments?: (number | Media)[] | null;
  sourcePage?: string | null;
  locale?: string | null;
  referrer?: string | null;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    term?: string | null;
    content?: string | null;
  };
  consentAt?: string | null;
  firstResponseAt?: string | null;
  closedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * سجل تلقائي بكل ملاحظة أو تغيير حالة على طلب — للقراءة والإضافة فقط.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-activities".
 */
export interface LeadActivity {
  id: number;
  lead: number | Lead;
  type: 'note' | 'status-change' | 'assignment' | 'call' | 'email' | 'visit';
  note?: string | null;
  fromStatus?: string | null;
  toStatus?: string | null;
  actor?: (number | null) | User;
  occurredAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  department?: string | null;
  city?: string | null;
  descriptionAr?: string | null;
  descriptionEn?: string | null;
  open?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: number;
  vacancy?: (number | null) | Career;
  name: string;
  email: string;
  phone: string;
  areaOfInterest: string;
  message?: string | null;
  cv?: (number | null) | Media;
  consentAt?: string | null;
  status?: ('new' | 'reviewing' | 'interview' | 'rejected' | 'hired') | null;
  notes?: string | null;
  assignedTo?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  /**
   * الاسم/المسمى — أو وصف عام إذا طُلبت السرية.
   */
  attribution: string;
  organization?: string | null;
  sector?: (number | null) | Sector;
  approved?: boolean | null;
  /**
   * لا يظهر أي عنصر بحالة غير "موثّق ومعتمد" في الموقع العام.
   */
  verificationStatus: 'unverified' | 'pending' | 'verified' | 'rejected';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * لا يظهر أي شعار في "عملاؤنا" إلا إذا كان usageApproved مفعّلًا هنا وعلى ملف الصورة نفسه.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  logo: number | Media;
  sector?: (number | null) | Sector;
  serviceLabel?: string | null;
  usageApproved?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * شهادات ISO وغيرها. لا تُعرض للعامة حتى يتم رفع نسخة سارية وتفعيل الظهور العام.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  /**
   * مثال: ISO 9001:2015
   */
  code: string;
  labelAr?: string | null;
  labelEn?: string | null;
  issuer?: string | null;
  certificateNumber?: string | null;
  issuedAt?: string | null;
  expiresAt?: string | null;
  /**
   * نسخة الشهادة الفعلية (PDF/صورة).
   */
  document?: (number | null) | Media;
  publicVisibility?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  roleAr?: string | null;
  roleEn?: string | null;
  photo?: (number | null) | Media;
  sortOrder?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * المسار القديم، مثال: /ar/old-page
   */
  from: string;
  /**
   * المسار الجديد أو رابط كامل.
   */
  to: string;
  type?: ('301' | '302') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * سجل تلقائي للعمليات الحساسة — للقراءة فقط، لا يمكن تعديله من الواجهة.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  actor?: (number | null) | User;
  action: string;
  collectionSlug?: string | null;
  documentId?: string | null;
  /**
   * وصف مختصر لا يحتوي أسرارًا أو بيانات شخصية كاملة.
   */
  safeSummary?: string | null;
  timestamp: string;
}
/**
 * بيانات مجمّعة يوميًا من مزود التحليلات المربوط — للقراءة فقط.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-daily".
 */
export interface AnalyticsDaily {
  id: number;
  date: string;
  pageViews?: number | null;
  visitors?: number | null;
  sessions?: number | null;
  quoteStarts?: number | null;
  quoteSubmits?: number | null;
  phoneClicks?: number | null;
  whatsappClicks?: number | null;
  topPages?:
    | {
        path?: string | null;
        views?: number | null;
        id?: string | null;
      }[]
    | null;
  deviceBreakdown?: {
    desktop?: number | null;
    mobile?: number | null;
    tablet?: number | null;
  };
  source?: ('ga4' | 'posthog') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'lead-activities';
        value: number | LeadActivity;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'analytics-daily';
        value: number | AnalyticsDaily;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  featured?: T;
  sortOrder?: T;
  summary?: T;
  heroOutcome?: T;
  problem?: T;
  scope?:
    | T
    | {
        item?: T;
        id?: T;
      };
  sectors?: T;
  methodology?: T;
  quality?: T;
  heroImage?: T;
  gallery?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  sortOrder?: T;
  summary?: T;
  challenges?:
    | T
    | {
        item?: T;
        id?: T;
      };
  relevantSolutions?: T;
  operatingModel?: T;
  media?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  verificationStatus?: T;
  workflowStatus?: T;
  confidentialityMode?: T;
  clientDisplayName?: T;
  sector?: T;
  relatedSolutions?: T;
  city?: T;
  contractStartDate?: T;
  contractEndDate?: T;
  durationLabel?: T;
  challenge?: T;
  scope?: T;
  solutionApproach?: T;
  kpis?:
    | T
    | {
        label?: T;
        beforeValue?: T;
        afterValue?: T;
        sourceNote?: T;
        id?: T;
      };
  gallery?: T;
  testimonial?:
    | T
    | {
        quote?: T;
        attribution?: T;
        approved?: T;
      };
  approvalEvidence?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  cover?: T;
  category?: T;
  tags?: T;
  author?: T;
  readingTimeMinutes?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  topic?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  referenceNumber?: T;
  type?: T;
  status?: T;
  priority?: T;
  assignedTo?: T;
  followUpAt?: T;
  lossReason?: T;
  name?: T;
  company?: T;
  email?: T;
  phone?: T;
  preferredContact?: T;
  service?: T;
  serviceSlug?: T;
  sector?: T;
  sectorSlug?: T;
  city?: T;
  message?: T;
  attachments?: T;
  sourcePage?: T;
  locale?: T;
  referrer?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
      };
  consentAt?: T;
  firstResponseAt?: T;
  closedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-activities_select".
 */
export interface LeadActivitiesSelect<T extends boolean = true> {
  lead?: T;
  type?: T;
  note?: T;
  fromStatus?: T;
  toStatus?: T;
  actor?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  city?: T;
  descriptionAr?: T;
  descriptionEn?: T;
  open?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  vacancy?: T;
  name?: T;
  email?: T;
  phone?: T;
  areaOfInterest?: T;
  message?: T;
  cv?: T;
  consentAt?: T;
  status?: T;
  notes?: T;
  assignedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  organization?: T;
  sector?: T;
  approved?: T;
  verificationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  sector?: T;
  serviceLabel?: T;
  usageApproved?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  code?: T;
  labelAr?: T;
  labelEn?: T;
  issuer?: T;
  certificateNumber?: T;
  issuedAt?: T;
  expiresAt?: T;
  document?: T;
  publicVisibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  roleAr?: T;
  roleEn?: T;
  photo?: T;
  sortOrder?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  altAr?: T;
  altEn?: T;
  captionAr?: T;
  captionEn?: T;
  credit?: T;
  category?: T;
  tags?: T;
  usageApproved?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  collectionSlug?: T;
  documentId?: T;
  safeSummary?: T;
  timestamp?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-daily_select".
 */
export interface AnalyticsDailySelect<T extends boolean = true> {
  date?: T;
  pageViews?: T;
  visitors?: T;
  sessions?: T;
  quoteStarts?: T;
  quoteSubmits?: T;
  phoneClicks?: T;
  whatsappClicks?: T;
  topPages?:
    | T
    | {
        path?: T;
        views?: T;
        id?: T;
      };
  deviceBreakdown?:
    | T
    | {
        desktop?: T;
        mobile?: T;
        tablet?: T;
      };
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    title: string;
    subtitle: string;
    ctaPrimaryLabel: string;
    ctaSecondaryLabel: string;
    image?: (number | null) | Media;
  };
  partnerSection?: {
    title?: string | null;
    subtitle?: string | null;
  };
  outcomesSection?: {
    title?: string | null;
    subtitle?: string | null;
  };
  /**
   * لا يظهر في الرئيسية إلا إذا كان هذا المشروع منشورًا وverificationStatus = verified.
   */
  featuredCaseStudy?: (number | null) | Project;
  /**
   * فعّله فقط بعد إضافة شعارات عملاء معتمدة usageApproved في مجموعة Clients.
   */
  showClientsSection?: boolean | null;
  homeCareBanner?: {
    title?: string | null;
    subtitle?: string | null;
    ctaLabel?: string | null;
  };
  finalCta?: {
    title?: string | null;
    subtitle?: string | null;
    buttonLabel?: string | null;
  };
  /**
   * عنوان ووصف الصفحة في نتائج البحث ومشاركات التواصل.
   */
  seo?: {
    /**
     * 60 حرفًا تقريبًا. اتركه فارغًا لاستخدام العنوان الافتراضي.
     */
    metaTitle?: string | null;
    /**
     * 155 حرفًا تقريبًا.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title: string;
  subtitle: string;
  story: {
    title: string;
    body: string;
    image?: (number | null) | Media;
  };
  missionSection: {
    sectionTitle: string;
    visionLabel: string;
    visionBody: string;
    missionLabel: string;
    missionBody: string;
  };
  values?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * عنوان قسم القيم، مثال: قيمنا.
   */
  valuesLabel?: string | null;
  /**
   * الصورة الجانبية بجوار مربّع "لماذا اجتياز الخليج".
   */
  sideImage?: (number | null) | Media;
  whyTitle: string;
  why?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * عنوان ووصف الصفحة في نتائج البحث ومشاركات التواصل.
   */
  seo?: {
    /**
     * 60 حرفًا تقريبًا. اتركه فارغًا لاستخدام العنوان الافتراضي.
     */
    metaTitle?: string | null;
    /**
     * 155 حرفًا تقريبًا.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quality-safety-page".
 */
export interface QualitySafetyPage {
  id: number;
  title: string;
  subtitle: string;
  heroImage?: (number | null) | Media;
  commitments?:
    | {
        title: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  certificationsSection: {
    title: string;
    /**
     * نص توضيحي يظهر أسفل الشهادات — مثال: حالة التحقق من الشهادات.
     */
    note?: string | null;
  };
  /**
   * عنوان ووصف الصفحة في نتائج البحث ومشاركات التواصل.
   */
  seo?: {
    /**
     * 60 حرفًا تقريبًا. اتركه فارغًا لاستخدام العنوان الافتراضي.
     */
    metaTitle?: string | null;
    /**
     * 155 حرفًا تقريبًا.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  topBar?: {
    locationAr?: string | null;
    locationEn?: string | null;
    availabilityAr?: string | null;
    availabilityEn?: string | null;
  };
  navItems?:
    | {
        labelAr: string;
        labelEn: string;
        /**
         * مسار نسبي بدون locale، مثال: /solutions
         */
        path: string;
        id?: string | null;
      }[]
    | null;
  ctaLabelAr?: string | null;
  ctaLabelEn?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  descriptionAr?: string | null;
  descriptionEn?: string | null;
  columns?:
    | {
        titleAr: string;
        titleEn: string;
        links?:
          | {
              labelAr: string;
              labelEn: string;
              path: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  nameAr: string;
  /**
   * TODO_VERIFY: الاسم القانوني الإنجليزي المعتمد لم يُؤكَّد بعد.
   */
  nameEn: string;
  nameEnStatus?: ('pending' | 'confirmed') | null;
  foundedYear?: number | null;
  foundedCityAr?: string | null;
  foundedCityEn?: string | null;
  /**
   * TODO_VERIFY
   */
  commercialRegistrationNumber?: string | null;
  /**
   * TODO_VERIFY
   */
  vatNumber?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings".
 */
export interface ContactSetting {
  id: number;
  phone?: string | null;
  phoneDisplay?: string | null;
  phoneStatus?: ('pending' | 'confirmed') | null;
  whatsapp?: string | null;
  whatsappStatus?: ('pending' | 'confirmed') | null;
  email?: string | null;
  emailStatus?: ('pending' | 'confirmed') | null;
  addressAr?: string | null;
  addressEn?: string | null;
  addressStatus?: ('pending' | 'confirmed') | null;
  workingHoursAr?: string | null;
  workingHoursEn?: string | null;
  socials?: {
    instagram?: string | null;
    linkedin?: string | null;
    x?: string | null;
  };
  /**
   * شريط الشهادات المختصر في الهيدر/الفوتر (تفاصيلها الكاملة في مجموعة Certifications).
   */
  certifications?:
    | {
        code?: string | null;
        labelAr?: string | null;
        labelEn?: string | null;
        status?: ('pending' | 'confirmed') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: number;
  defaultMetaTitleAr?: string | null;
  defaultMetaTitleEn?: string | null;
  defaultMetaDescriptionAr?: string | null;
  defaultMetaDescriptionEn?: string | null;
  defaultOgImage?: (number | null) | Media;
  googleSiteVerification?: string | null;
  /**
   * أسطر إضافية تُلحق بملف robots.txt عند الحاجة.
   */
  robotsExtraRules?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings".
 */
export interface AnalyticsSetting {
  id: number;
  provider?: ('none' | 'ga4' | 'posthog') | null;
  ga4MeasurementId?: string | null;
  /**
   * لسحب تقارير GA4 Data API لعرضها في اللوحة.
   */
  ga4PropertyId?: string | null;
  posthogProjectApiKey?: string | null;
  posthogHost?: string | null;
  cookieConsentRequired?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings".
 */
export interface NotificationSetting {
  id: number;
  /**
   * البريد الذي يستقبل تنبيه عند وصول طلب جديد.
   */
  teamNotificationEmail?: string | null;
  slaResponseTextAr?: string | null;
  slaResponseTextEn?: string | null;
  notifyOnNewLead?: boolean | null;
  notifyOnNewJobApplication?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ctaPrimaryLabel?: T;
        ctaSecondaryLabel?: T;
        image?: T;
      };
  partnerSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  outcomesSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  featuredCaseStudy?: T;
  showClientsSection?: T;
  homeCareBanner?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ctaLabel?: T;
      };
  finalCta?:
    | T
    | {
        title?: T;
        subtitle?: T;
        buttonLabel?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  story?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
      };
  missionSection?:
    | T
    | {
        sectionTitle?: T;
        visionLabel?: T;
        visionBody?: T;
        missionLabel?: T;
        missionBody?: T;
      };
  values?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  valuesLabel?: T;
  sideImage?: T;
  whyTitle?: T;
  why?:
    | T
    | {
        item?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quality-safety-page_select".
 */
export interface QualitySafetyPageSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  heroImage?: T;
  commitments?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  certificationsSection?:
    | T
    | {
        title?: T;
        note?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  topBar?:
    | T
    | {
        locationAr?: T;
        locationEn?: T;
        availabilityAr?: T;
        availabilityEn?: T;
      };
  navItems?:
    | T
    | {
        labelAr?: T;
        labelEn?: T;
        path?: T;
        id?: T;
      };
  ctaLabelAr?: T;
  ctaLabelEn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  descriptionAr?: T;
  descriptionEn?: T;
  columns?:
    | T
    | {
        titleAr?: T;
        titleEn?: T;
        links?:
          | T
          | {
              labelAr?: T;
              labelEn?: T;
              path?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  nameAr?: T;
  nameEn?: T;
  nameEnStatus?: T;
  foundedYear?: T;
  foundedCityAr?: T;
  foundedCityEn?: T;
  commercialRegistrationNumber?: T;
  vatNumber?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-settings_select".
 */
export interface ContactSettingsSelect<T extends boolean = true> {
  phone?: T;
  phoneDisplay?: T;
  phoneStatus?: T;
  whatsapp?: T;
  whatsappStatus?: T;
  email?: T;
  emailStatus?: T;
  addressAr?: T;
  addressEn?: T;
  addressStatus?: T;
  workingHoursAr?: T;
  workingHoursEn?: T;
  socials?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
        x?: T;
      };
  certifications?:
    | T
    | {
        code?: T;
        labelAr?: T;
        labelEn?: T;
        status?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  defaultMetaTitleAr?: T;
  defaultMetaTitleEn?: T;
  defaultMetaDescriptionAr?: T;
  defaultMetaDescriptionEn?: T;
  defaultOgImage?: T;
  googleSiteVerification?: T;
  robotsExtraRules?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-settings_select".
 */
export interface AnalyticsSettingsSelect<T extends boolean = true> {
  provider?: T;
  ga4MeasurementId?: T;
  ga4PropertyId?: T;
  posthogProjectApiKey?: T;
  posthogHost?: T;
  cookieConsentRequired?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings_select".
 */
export interface NotificationSettingsSelect<T extends boolean = true> {
  teamNotificationEmail?: T;
  slaResponseTextAr?: T;
  slaResponseTextEn?: T;
  notifyOnNewLead?: T;
  notifyOnNewJobApplication?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}